# Generated by Django 4.1.3 on 2022-11-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTitle', models.CharField(max_length=200)),
                ('eventSubtitle', models.CharField(max_length=200)),
                ('eventImageURL', models.CharField(max_length=200)),
                ('eventLinkURL', models.CharField(max_length=200)),
                ('eventCompany', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('eventType', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('imageURL', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
            ],
        ),
    ]
