# Generated by Django 4.1.3 on 2022-11-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvsinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventCompany',
        ),
    ]
