# Generated by Django 4.1.3 on 2022-11-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsinfo', '0002_remove_event_eventcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventCompany',
            field=models.CharField(default='', max_length=200),
        ),
    ]
