# Generated by Django 4.1.3 on 2022-11-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsinfo', '0004_remove_event_eventlinkurl_remove_event_eventsubtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterModelTable(
            name='event',
            table='event',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
