# Generated by Django 4.1.3 on 2022-11-21 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvsinfo', '0005_alter_product_price_alter_event_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventCompany',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventImageURL',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='eventTitle',
            new_name='name',
        ),
    ]
