# Generated by Django 4.1.3 on 2022-11-21 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cvsinfo', '0006_rename_eventcompany_event_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='imageUrl',
            new_name='imgUrl',
        ),
    ]
