# Generated by Django 4.1.2 on 2022-11-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvsinfo', '0007_rename_imageurl_event_imgurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imageURL',
            new_name='imgURL',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
